# Generated by Django 4.0.6 on 2022-07-10 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(default='no name', max_length=100, verbose_name='prod_name')),
                ('description', models.CharField(max_length=2000, verbose_name='description')),
                ('prod_category', models.CharField(choices=[('other', 'other'), ('audio/vidoe', 'Audio/Video'), ('tvs', 'TVs'), ('cell', 'Cell Phones')], default='other', max_length=20, verbose_name='prod_category')),
                ('balance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='balance')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
    ]
